# Generated by Django 5.0 on 2023-12-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Core", "0002_loan"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="approved_limit",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="current_debt",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
