# Generated by Django 5.0 on 2023-12-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Core", "0003_customer_age_alter_customer_approved_limit_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="id",
        ),
        migrations.AlterField(
            model_name="customer",
            name="customer_id",
            field=models.AutoField(
                db_column="customer_id", primary_key=True, serialize=False
            ),
        ),
    ]
