# Generated by Django 5.0 on 2023-12-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Core", "0005_alter_customer_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="approved_limit",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
