# Generated by Django 5.0 on 2023-12-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Core", "0006_alter_customer_approved_limit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="monthy_salary",
        ),
        migrations.AddField(
            model_name="customer",
            name="monthly_salary",
            field=models.BigIntegerField(default=50),
            preserve_default=False,
        ),
    ]
