# Generated by Django 5.0 on 2023-12-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Core", "0008_alter_loan_emi_paid_on_time_alter_loan_loan_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="interest_rate",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
